In [8]:
# Problem 1 
def dot(A,B):
    import numpy as np
    A=np.array([[3,-1,4],[1,5,-9]])
    B=np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])
    return np.dot(A,B)



In [10]:
>>> dot(A,B)


array([[ 37,  14, -32, -10],
       [ 87, -34,  13,  29]])

In [37]:
# Problem 2
def f():
    import numpy as np
    A=np.array([[3,1,4],[1,5,9],[-5,3,1]])
    B=np.dot(A,A)
    return 9*np.dot(A,A)-15*A-np.dot(A,B)



In [38]:
>>> f()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
# Problem 3
def g():
    import numpy as np
    A1=np.ones((7,7),dtype=np.int)
    A=np.triu(A1)
    B1=np.full_like(A,5)
    B2=np.full_like(A,-1)
    B3=np.tril(B2)
    B4=np.triu(B1)
    B5=np.diag([5,5,5,5,5,5,5])
    B6=B3+B4
    B=B6-B5
    AB=np.dot(A,B)
    matrix=np.dot(AB,A)
    matrix=matrix.astype(np.int64)
    return matrix 


In [61]:
>>> g()


array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

In [66]:
# Problem 4
def h(y):
    import numpy as np
    A=np.copy(y)
    mask=A<0
    A[mask]=0
    return A


In [69]:
h([1,1,1,0,-1,-1])

array([1, 1, 1, 0, 0, 0])

In [99]:
# Problem 5
def k():
    import numpy as np
    A=np.arange(6).reshape((2,-1))
    B1=np.zeros((3,3))
    B2=np.full_like(B1,3)
    B=np.tril(B2)
    C=np.diag([-2,-2,-2])
    I=np.diag([1,1,1])
    C1=np.vstack((np.zeros((3,3)),A,B))
    C2=np.vstack((A.T,np.zeros((2,2)),np.zeros((3,2))))
    C3=np.vstack((I,np.zeros((2,3)),C))
    matrix=np.hstack((C1,C2,C3))
    return matrix         
                
                 


In [100]:
k()

array([[ 0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  4.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  2.,  5.,  0.,  0.,  1.],
       [ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  4.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

In [132]:
# Problem 6
def j(A):
    import math
    import numpy as np
    A1=np.array(A) 
    B=A1.sum(axis=1).reshape((3,1))
    return A1/B


In [134]:
j([[1,1,1],[2,5,2],[3,3,3]])

array([[0.33333333, 0.33333333, 0.33333333],
       [0.22222222, 0.55555556, 0.22222222],
       [0.33333333, 0.33333333, 0.33333333]])

In [143]:
# Problem 7
def p():
    import numpy as np
    grid=np.load("grid.npy")
    A=np.max(grid[:,:-3]*grid[:,1:-2]*grid[:,2:-1]*grid[:,3:])
    B=np.max(grid[:-3,:]*grid[1:-2,:]*grid[2:-1,:]*grid[3:,:])
    C=np.max(grid[:-3,3:]*grid[1:-2,2:-1]*grid[2:-1,1:-2]*grid[3:,:-3])
    D=np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
    M=np.max([A,B,C,D])
    return M

In [144]:
p()

70600674