Exercise 1

We already have the Euler equation and the policy function. We can rewrite $k_{t+2}$ in terms of $k_{t+1}$: $$ k_{t+2}=Ae^{Zt+1}k_{t+1}^{a} $$and subsititute in the Euler equation. Now we have:
 $$ \frac{1}{(1-A)e^{Zt}K_{t}^a} = \beta E_{t}[\frac{ae^{Zt+1}K_{t+1}^{a-1}}{e^{Zt+1}K_{t+1}^a - Ae^{Zt+1}K_{t+1}^a}]$$ Hence: $$K_{t+1} = \beta a e^{Zt}K_{t}^a \Rightarrow A = \beta a$$

Exercise 2

Plugging in the functional forms gives us:
$$w_t(1-\tau)\frac{1}{c_t}) = \frac{a}{1-l_t}$$
$$\frac{1}{c_t} = \beta \mathbb{E} \big[ \frac{1}{c_{t+1}}[(r_{t+1}-\delta)(1-\tau) +1] \big]$$
$$R_t = \alpha e^{z_t} K^{\alpha - 1} L^{1-\alpha} $$
$$W_t = (1 - \alpha) e^{z_t} K^\alpha L^{-\alpha}$$
$$\tau[w_tl_t+(r_t - \delta)k_t] = T_t$$
Imposing market clearing conditions:
$$l_t = L_t $$
$$k_t = K_t $$
$$w_t = W_t $$
$$r_t = R_t $$
We can't use the same algebraic tricks to solve for A. 

Exercise 3

Plugging in the functional forms gives us :
$$w_t(1-\tau)c_t^{-\gamma} = \frac{a}{1-l_t} $$
$$c_t^{-\gamma} = \beta \mathbb{E} \big[ c_{t+1}^{-\gamma}[(r_{t+1}-\delta)(1-\tau) +1] \big]$$
$$R_t = \alpha e^{z_t} K_t^{\alpha - 1} L_T^{1-\alpha} $$
$$W_t = (1 - \alpha) e^{z_t} K_t^\alpha L_t^{-\alpha}$$
$$\tau[w_tl_t+(r_t - \delta)k_t] = T_t$$
market clearing conditions unchanged  


Exercise 4

$$w_t(1-\tau)c_t^{-\gamma} = -a(1-l_t)^{-\gamma} $$
$$c_t^{-\gamma} = \beta \mathbb{E} \big[ c_{t+1}^{-\gamma}[(r_{t+1}-\delta)(1-\tau) +1] \big]$$
$$R_t = e^z_t [\alpha K^{\eta}_t +(1-\alpha)L^{\eta}_t]^{\frac{1}{\eta} - 1} \alpha K_t^{\eta -1} $$
$$W_t = e^z_t [\alpha K^{\eta}_t +(1-\alpha)L^{\eta}_t]^{\frac{1}{\eta} - 1} (1-\alpha) L_t^{\eta -1}$$
$$\tau[w_tl_t+(r_t - \delta)k_t] = T_t$$
market clearing conditions unchaged 

Exercise 5

We have:
$$c_t^{-\gamma} = \beta \mathbb{E} \big[ c_{t+1}^{-\gamma}[(r_{t+1}-\delta)(1-\tau) +1] \big]$$
$$R_t = \alpha e^{\alpha z_t} K_t^{\alpha - 1} L_T^{1-\alpha} $$
$$W_t = (1 - \alpha) e^{\alpha z_t} K_t^\alpha L_t^{- \alpha}$$
$$\tau[w_t+(r_t - \delta)k_t] = T_t$$
market clearing conditions unchanged 

With $l_{t}=1$, in steady state we have:
$$c^{-\gamma} = \beta \mathbb{E} \big[ c^{-\gamma}[(r-\delta)(1-\tau)+1] \big] $$
$$r = \alpha e^{\alpha z} k^{\alpha - 1} $$
$$w = (1 - \alpha) e^{\alpha z} k^\alpha $$
$$\tau[w+(r - \delta)k] = T$$

Simply the Euler equation gives us:
$$ 1 = \beta [(ak^{\alpha-1}e^{{z\alpha}} - \delta)(1-\tau) +1]$$
With $z=0$ we have:
$$k = \big[\frac{\beta(1-\tau)\alpha}{(1-\beta) + \delta\beta(1-\tau)}\big]^{\frac{1}{1-\alpha}}$$

In [44]:
#parameters 
gamma = 2.5
beta = 0.98
alpha = 0.40
a = 0.5
delta = 0.10
tau = 0.05
a=0.5
xi=1.5

In [45]:
import numpy as np
import scipy.optimize as opt

In [8]:
#solve for the steady state values numerically 
def euler(k):
    eq = 1 - beta*((alpha*k**(alpha-1) - delta)*(1-tau)+1)
    return eq
def p5():
    root = opt.root(euler, 1,  tol=1e-8)
    answer = root.x
    return answer

In [10]:
k=p5()
k

array([7.28749795])

In [12]:
y=k**alpha
y

array([2.21325461])

In [13]:
i=delta*k
i

array([0.7287498])

Exercise 6

Plugging in the functional forms gives us :
$$w_t(1-\tau)c_t^{-\gamma} = \frac{\alpha}{{(1-l_t)}^{\xi}} $$
$$c_t^{-\gamma} = \beta \mathbb{E} \big[ c_{t+1}^{-\gamma}[(r_{t+1}-\delta)(1-\tau) +1] \big]$$
$$R_t = \alpha{e^{z_t}}^{1-a} K_t^{\alpha - 1} L_T^{1-\alpha} $$
$$W_t = (1 - \alpha) {(e^{z_t})}^{1-a} K_t^\alpha L_t^{-\alpha}$$
$$\tau[w_tl_t+(r_t - \delta)k_t] = T_t$$
market clearing conditions unchanged  

In [54]:
#solve problem 6 numerically 
def get_cbar(w, r, guess):
    c_bar = w * guess[1] + (r - delta) * guess[0]
    return c_bar

def get_rbar(guess):
    r_bar = alpha * (guess[1]/guess[0]) ** (1 - alpha) * (np.exp(0)) ** (1 - alpha)
    return r_bar

def get_wbar(guess):
    w_bar = (1 - alpha) * (guess[0]/guess[1]) ** alpha * (np.exp(0)) ** (1 - alpha)
    return w_bar
def euler_6(guess):
    w = get_wbar(guess)
    r = get_rbar(guess)
    c = get_cbar(w, r, guess)
    eq1 = c ** (-gamma) - beta * (c ** (-gamma)* ((1 - tau) * (r - delta) + 1))
    eq2 = a * (1 - guess[1]) ** (-1*xi) - c ** (-gamma) * w * (1 - tau)  
    errors = np.array([eq1, eq2])
    return errors 
    
    
    

In [61]:
guess=np.array([1, 0.9])
result = opt.root(euler_6, guess,tol=1e-8)
print("steady state k is:",k)
print("steady state l is: ",l)
k,l=result.x

steady state k is: 4.225229026915344
steady state l is:  0.5797914531683577
