# Problem 1

In [68]:
import numpy as np
def check(c, A, b):
    if any(b < 0)==True:
        raise ValueError
    else:
        pass


In [69]:
A = np.array([[1, -1], [3, 1], [4, 3]])
b = np.array([2, 5, 7])
c = np.array([3, 2])

# Problem 2

In [70]:
def index(A):
    m, n = A.shape
    a = np.arange(n, n + m)
    b = np.arange(0, n)
    L = np.hstack([a, b])
    L = np.ndarray.tolist(L)
    return L

L = index(A)
print(L)

[2, 3, 4, 0, 1]


# Problem 3


In [71]:
def get_tableau(c, A, b):
    m, n = A.shape
    c_bar = np.concatenate([c, np.zeros(m)])
    c_bar = -1 * c_bar
    T1 = np.concatenate([np.array([0]), c_bar, np.array([1])])
    A_bar = np.concatenate([A, np.eye(m)], axis = 1)
    T2 = np.hstack([b.reshape(len(b), 1), A_bar, np.zeros((m, 1))])
    T = np.vstack([T1, T2])
    return T



In [72]:
T = get_tableau(c, A, b)
print(T)

[[ 0. -3. -2. -0. -0. -0.  1.]
 [ 2.  1. -1.  1.  0.  0.  0.]
 [ 5.  3.  1.  0.  1.  0.  0.]
 [ 7.  4.  3.  0.  0.  1.  0.]]


# Problem 4

In [73]:
def pivot(T):
    p, q = T.shape
    T1 = T[0, 1:]
    column = np.where(T1 < 0)[0][0] + 1
    if any(T[:, column] > 0)== False:
        raise ValueError
    else:
        loc = np.where(T[:, column] > 0)[0]
        n = len(loc)
        mat = np.zeros(n) 
        for i in range(n):
            mat[i] = float(T[loc[i], 0]/T[loc[i], column])
        m = np.where(mat==min(mat))[0][0]
        row = loc[m]+1
        
    return row , column+1 



In [74]:
pivot(T)

(3, 2)

# Problem 5

In [75]:
def op(T, L):
    T1 = np.copy(T)
    m, n = pivot(T)
    a, b = m - 2, L.index(n - 2) 
    p, q = T.shape
    m = m - 1
    n = n - 1
    if T[m, n] != 0:
         T1[m,:] = T[m, :]/float(T[m, n])
    for i in range(p):
        if i == m or T[i, n] == 0:
            T1[i, :] = T1[i, :]
        else:
            T1[i, :] = T1[i, :] - float((T1[i, n]/T1[m, n])) * T1[m, :]
       
    else:
         T1[m,:] = T[m, :]
       
    L[a], L[b] = L[b], L[a]
    return T1, L

op(T, L)

(array([[ 5.        ,  0.        , -1.        ,  0.        ,  1.        ,
          0.        ,  1.        ],
        [ 0.33333333,  0.        , -1.33333333,  1.        , -0.33333333,
          0.        ,  0.        ],
        [ 5.        ,  3.        ,  1.        ,  0.        ,  1.        ,
          0.        ,  0.        ],
        [ 0.33333333,  0.        ,  1.66666667,  0.        , -1.33333333,
          1.        ,  0.        ]]), [2, 0, 4, 3, 1])

# Problem 6

In [76]:
def solve(T, L):
    tol = -1e-8
    while any(T[0, 1:] < tol) == True:
        T_new, L_new = op(T, L)
        T = np.copy(T_new)
        L = L_new
    value = np.ndarray.tolist(T[1:,0])
    n = len(value)
    D1 = dict(zip(L[:n], [float(str(round(i, 2))) for i in value]))
    D2 = dict(zip((L[n:]), np.zeros(len(L) - n)))
    return float(T[0,0]), D1, D2



In [77]:
solve(T, L)

(5.2, {2: 0.6, 0: 4.8, 1: 0.33}, {3: 0.0, 4: 0.0})

# Problem 7

In [78]:
data = np.load('productMix.npz')
A = data['A']
p = data['p']
m = data['m']
d = data['d']


In [79]:
A = np.vstack([A, np.eye(4)])
b = np.hstack([m, d])
L = index(A)
T = tableau(p, A, b)
solve(T, L)

(7453.596491228071,
 {1: 1.11, 3: 0.11, 6: 0.97, 0: 10.0, 8: 13.81, 2: 12.0, 10: 8.21},
 {7: 0.0, 4: 0.0, 9: 0.0, 5: 0.0})